In [52]:
import torch 
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from VAN import *


In [1]:
taille=6
## différentes distributions de probabilité
def p(s):
    if torch.eq(s, torch.tensor([1.0, 1.0, 1.0, 0.0, 0.0, 0.0])).all().item():
        return 0.469
    elif torch.eq(s, torch.tensor([0.0, 0.0, 0.0, 1.0, 1.0, 1.0])).all().item():
        return 0.469
    else:
        
        return 0.001
    
def p2(s):
    return 1/(2**6)

def p3(s):
    if torch.eq(s, torch.tensor([1.0, 1.0, 1.0, 0.0, 0.0, 0.0])).all().item():
        return 0.75
    elif torch.eq(s, torch.tensor([0.0, 0.0, 0.0, 1.0, 1.0, 1.0])).all().item():
        return 0.25
    else:
        return 0.001


Epoch 0: 2.2798728942871094
Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.1000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.1000,  0.1000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.1000, -0.1000, -0.1000,  0.0000,  0.0000,  0.0000],
        [-0.1000, -0.1000, -0.1000, -0.1000,  0.0000,  0.0000],
        [-0.1000, -0.1000, -0.1000,  0.0000, -0.1000,  0.0000]],
       requires_grad=True)
Parameter containing:
tensor([ 0.1000,  0.1000,  0.1000, -0.1000, -0.1000, -0.1000],
       requires_grad=True)
Epoch 20: 0.25416499376296997
Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.9744,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.8243,  1.6083,  0.0000,  0.0000,  0.0000,  0.0000],
        [-1.7672, -1.4058, -1.1189,  0.0000,  0.0000,  0.0000],
        [-1.7194, -1.3678, -1.0805,  1.2077,  0.0000,  0.0000],
        [-1.6865, -1.3900, -1.1685,  1.2876,  1.1913, 

In [ ]:
mymodel=VAN(taille, torch.sigmoid)

l=train(mymodel, p, n_iter=200, lr=1e-1, train_size=100)

plt.plot(l)

In [4]:
y1=(torch.tensor([1.0, 1.0, 1.0, 0.0, 0.0, 0.0]))
y2=(torch.tensor([0.0, 0.0, 0.0, 0.0, 0.0, 0.0]))
y3=(torch.tensor([0., 0., 0., 0., 0., 1.]))
y4=(torch.tensor([0., 0., 0., 1., 1., 1.]))

In [10]:
calculer_proba(y4, mymodel)

0.5029874263654445